--
-- PostgreSQL database dump
--

\restrict COhnRar5tl0Mn8V9F9n2y7eE0dbjVGl7llVjYqdvBctRxdSo5CGfeK0FyxoaX9g

-- Dumped from database version 18.0 (Debian 18.0-1.pgdg13+3)
-- Dumped by pg_dump version 18.0 (Debian 18.0-1.pgdg13+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: productos; Type: TABLE; Schema: public; Owner: medicinaApp
--

CREATE TABLE public.productos (
    id bigint NOT NULL,
    descripcion character varying(255),
    nombre character varying(255),
    precio double precision NOT NULL,
    stock integer NOT NULL,
    imagen_url character varying(255),
    categoria character varying(255)
);


ALTER TABLE public.productos OWNER TO "medicinaApp";

--
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: medicinaApp
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: medicinaApp
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    correo character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL
);


ALTER TABLE public.usuarios OWNER TO "medicinaApp";

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: medicinaApp
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: medicinaApp
--

COPY public.productos (id, descripcion, nombre, precio, stock, imagen_url, categoria) FROM stdin;
341	Concentrado premium para perros adultos de razas medianas.	Royal Canin Medium Adult 4kg	135000	18	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/111102978-v1-min.jpg	Alimentaci├│n
342	Alimento balanceado para perros adultos de razas grandes.	Royal Canin Maxi Adult 4kg	142000	18	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/111100542-v1-min.jpg	Alimentaci├│n
343	Concentrado completo para perros adultos con prote├¡nas de calidad.	Dog Chow Adultos 8kg	78000	25	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/111100220_ed-min.jpg	Alimentaci├│n
344	Alimento balanceado para cachorros en crecimiento.	Dog Chow Cachorros 8kg	82000	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/111103179_ed-min.jpg	Alimentaci├│n
345	Alimento seco completo para perros adultos de razas peque├▒as con prote├¡nas y vitaminas esenciales.	Pedigree Adulto Raza Peque├▒a 4kg	58000	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/9/1/912000040-min.jpg	Alimentaci├│n
346	Alimento balanceado para cachorros en crecimiento que ayuda al desarrollo de huesos y m├║sculos.	Pedigree Cachorro 4kg	62000	18	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/9/1/912000041-min.jpg	Alimentaci├│n
347	Alimento seco para perros adultos con pollo y arroz que favorece la digesti├│n.	Chunky Adultos Pollo y Arroz 9kg	95000	15	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/9/1/910000057-min.jpg	Alimentaci├│n
348	Alimento para perros adultos con alta actividad f├¡sica que ayuda a mantener energ├¡a y vitalidad.	Chunky Adulto Vida Activa 8kg	92000	15	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/9/1/910000063-min.jpg	Alimentaci├│n
349	Concentrado especializado para perros adultos de razas peque├▒as.	Chunky Adulto Razas Peque├▒as Pollo y Arroz 8kg	96000	15	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/9/1/910000060-min.jpg	Alimentaci├│n
350	Alimento para cachorros con prote├¡nas de alta calidad para un crecimiento saludable.	Chunky Cachorros Cordero Arroz y Salm├│n 8kg	98000	14	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/9/1/910000066-min.jpg	Alimentaci├│n
351	Alimento seco premium para gatos esterilizados con control de peso.	Max Cat Premium Gatos Castrados Pollo 3kg	52000	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/9/1/911000209-min.jpg	Alimentaci├│n
352	Alimento balanceado para gatos adultos con prote├¡nas y nutrientes esenciales.	Max Cat Adultos Pollo y Arroz 3kg	49000	18	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/9/1/911000212-min.jpg	Alimentaci├│n
353	Alimento seco especialmente formulado para gatitos en crecimiento.	Max Cat Gatitos Pollo 1kg	22000	22	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/9/1/911000213-min.jpg	Alimentaci├│n
354	Alimento h├║medo veterinario para perros con problemas digestivos.	Hills Prescription Diet Digestive Care i/d 13oz	16000	25	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/111100077-v1-min.jpg	Alimentaci├│n
355	Alimento seco para perros senior con nutrientes que apoyan articulaciones y digesti├│n.	Nutra Nuggets Senior Pollo 15kg	210000	10	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/111100366_ed-min.jpg	Alimentaci├│n
356	Alimento h├║medo veterinario para perros con sensibilidad digestiva.	Monge Vet Solution Gastrointestinal 150g	13500	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/111103321-v2-min.jpg	Alimentaci├│n
357	Alimento h├║medo premium para gatos adultos con sabor a salm├│n.	Pro Plan Wet Salm├│n Gatos 85g	6500	40	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/111103351_ed-min.jpg	Alimentaci├│n
358	Alimento h├║medo para gatos con textura tipo pat├® sabor salm├│n.	Felix Pat├® Salm├│n 156g	7000	35	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/111110352_ed-min.jpg	Alimentaci├│n
359	Alimento h├║medo premium para gatitos en crecimiento.	Royal Canin Kitten Lata 85g	8500	35	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/111111299_ed-min.jpg	Alimentaci├│n
360	Alimento h├║medo gourmet para gatos adultos con sabor a at├║n y salm├│n.	Fancy Feast At├║n y Salm├│n 85g	6500	35	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/111111481-min.jpg	Alimentaci├│n
361	Shampoo dermatol├│gico para perros y gatos que ayuda a mantener la piel saludable.	Shampoo Keracleen 240ml	42000	15	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/_/5/_5_7_5757457415741000031.jpg	Higiene
362	Shampoo medicado para perros y gatos con acci├│n antibacteriana.	Shampoo Baxidin 250ml	38000	15	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/_/5/_5_7_5757457415741000328_1-min.jpg	Higiene
363	Cepillo para remover pelo muerto y desenredar el pelaje de perros y gatos.	Cepillo Slicker Large	22000	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/_/3/_3_1_313100091.jpg	Higiene
364	Jab├│n para perros y gatos con aceite de ├írbol de t├® que ayuda a limpiar y desinfectar.	Jab├│n ├ürbol de T├® Mascotas 90g	12000	25	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/_/5/_5_7_5757457405740000003-min.jpg	Higiene
365	Talco desodorante para mascotas que ayuda a mantener el pelaje limpio sin necesidad de agua.	CanAmor Ba├▒o Seco Talco Desodorante 100g	18000	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/_/5/_5_7_5757457425742000004-min.jpg	Higiene
366	Shampoo suave para perros y gatos que limpia y mantiene el pelaje brillante.	Shampoo Petys Limpieza y Suavidad 235ml	16000	22	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/5/7/5757457415741000511_ed-min.jpg	Higiene
367	Guante de aseo que permite retirar el pelo muerto de perros y gatos.	Guante Removedor de Pelo Dog Grooming	24000	18	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/1/313100254-v1-min.jpg	Higiene
368	Pa├▒itos h├║medos con clorhexidina para la limpieza de mascotas.	Toallitas H├║medas Petys Clorhexidina 40und	15000	25	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/5/353520451-v1-min.jpg	Higiene
369	Arena sanitaria para gatos con aroma que ayuda a controlar olores.	Arena para Gatos Maxicat 10kg Aroma Beb├®	34000	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/1/313120461-v1-min.jpg	Higiene
370	Pelota resistente para perros con sonido squeaker que estimula el juego y la actividad f├¡sica.	Chuckit Ultra Squeaker Ball Perro Talla S	28000	25	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/3/333304191-min.jpg	Juguetes
371	Pelota interactiva que dispensa alimento o snacks mientras el perro juega.	Pelota Dispensadora de Snacks para Perros 11cm	24000	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/_/3/_3_3_333310072-_4__ed-min.jpg	Juguetes
372	Juguete mordedor dise├▒ado para fortalecer dientes y enc├¡as en perros.	Hueso Dental para Perros Ferplast	22000	18	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/3/333311039-min.jpg	Juguetes
373	Juguete de peluche suave para perros ideal para juegos de compa├▒├¡a.	Peluche Alpaca para Perros	26000	18	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/3/333303245-min.jpg	Juguetes
374	Juguete de peluche con caucho termopl├ístico resistente para perros.	Peluche Le├│n Gigwi Plush Friendz	32000	16	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/3/333304250-min.jpg	Juguetes
375	Juguete de peluche resistente para perros ideal para juego interactivo.	Peluche Alpaca para Perro 22cm	27000	16	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/3/333310891_1_-min.jpg	Juguetes
376	Juguete de peluche con sonido para estimular el juego en perros.	Peluche Hippo Suppa Puppa	29000	15	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/3/333303870-min.jpg	Juguetes
377	Juguete interactivo para gatos que estimula el instinto de caza.	Juguete Arco├¡ris para Gatos	14000	30	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/_/3/_3_3_333301088.jpg	Juguetes
378	Pelota ligera para gatos ideal para juegos de persecuci├│n.	Pelota Espiral para Gatos 4.5cm	9000	35	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/3/333303916-min.jpg	Juguetes
379	Juguete tipo erizo con textura para estimular el juego en gatos.	Pelota Erizo Trixie para Gatos	11000	30	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/3/333310953-min.jpg	Juguetes
380	Juguete para gatos con forma de rat├│n ideal para estimular la caza.	Rat├│n de Cuerda para Gatos Trixie	10000	30	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/3/333301001-min.jpg	Juguetes
381	Arn├®s c├│modo y seguro para paseos con perros.	Arn├®s Trekking para Perros Trixie S-M	42000	15	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/2/323215584-min.jpg	Accesorios
382	Arn├®s para perros con dise├▒o c├│modo y resistente.	Arn├®s Pechera Toby Totto Pets Talla M	46000	15	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/2/323215187-min.jpg	Accesorios
383	Correa resistente para paseos seguros con mascotas.	Correa para Perros Animal Factor Azul	25000	18	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/2/323213492-min.jpg	Accesorios
384	Arn├®s resistente dise├▒ado para mayor control y seguridad.	Arn├®s Lona Premium para Perros XL	45000	12	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/1/1/119000114-min.jpg	Accesorios
385	Placa de identificaci├│n para colocar informaci├│n de la mascota.	Placa de Identificaci├│n para Mascotas Azul	15000	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/2/323240220-min.jpg	Accesorios
386	Placa met├ílica para identificaci├│n de mascotas.	Placa de Identificaci├│n Shine Negra	16000	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/2/323240510-min.jpg	Accesorios
387	Collar reflectivo con broche de seguridad para gatos.	Collar Reflectivo para Gato Trixie	18000	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/2/323212453-min.jpg	Accesorios
388	Collar ajustable para gatos con dise├▒o c├│modo.	Collar Kitty Cat para Gatos	16000	20	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/2/323210235-min.jpg	Accesorios
389	Arn├®s ajustable para gatos con correa incluida.	Arn├®s para Gato Trixie 24-42cm	32000	15	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/2/323212629-min.jpg	Accesorios
340	Alimento seco premium para perros adultos de razas peque├▒as.	Royal Canin Mini Adult 2kg	95000	20	https://www.tierragro.com/cdn/shop/files/3182550793612_5afda598-88d4-4d90-8525-04ef3e874f1a_1800x1800.png?v=1743527471	Alimentaci├│n
390	Trixie Gimnasio para gato Morella Alt 96 cm Beige 	Trixie Gimnasio para gato	339600	10	https://www.agrocampo.com.co/media/catalog/product/cache/dd0974c17aa11c1008feb0c4f8e4080c/3/3/333303610_1_-min.jpg	Accesorios
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: medicinaApp
--

COPY public.usuarios (id, password, role, username, correo, nombre) FROM stdin;
3	$2a$10$7hgHKmoM3jV3qiOiilHAF.XUxZttTSaSXEriXzQlaj18zPj9u0AI6	ROLE_ADMIN	admin	admin@happypet.com	Administrador
2	$2a$10$7hgHKmoM3jV3qiOiilHAF.XUxZttTSaSXEriXzQlaj18zPj9u0AI6	ROLE_CLIENTE	Dav1	dv1@gmail.com	David Esteban Perez
37	$2a$10$rR5YlCSkqxRIx0o5hFiXIeW.h5xFAhs1n9JlvKsSkTBpeCkGD31Ju	CLIENTE	dani	da@gmail.com	Daniela Casta├▒eda
\.


--
-- Name: productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medicinaApp
--

SELECT pg_catalog.setval('public.productos_id_seq', 390, true);


--
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: medicinaApp
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 37, true);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: medicinaApp
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- Name: usuarios ukcdmw5hxlfj78uf4997i3qyyw5; Type: CONSTRAINT; Schema: public; Owner: medicinaApp
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukcdmw5hxlfj78uf4997i3qyyw5 UNIQUE (correo);


--
-- Name: usuarios ukm2dvbwfge291euvmk6vkkocao; Type: CONSTRAINT; Schema: public; Owner: medicinaApp
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukm2dvbwfge291euvmk6vkkocao UNIQUE (username);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: medicinaApp
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict COhnRar5tl0Mn8V9F9n2y7eE0dbjVGl7llVjYqdvBctRxdSo5CGfeK0FyxoaX9g

