spring.datasource.url=jdbc:postgresql://happypet-db.cile4ue20vzn.us-east-1.rds.amazonaws.com:5432/happypet
spring.datasource.username=postgres
spring.datasource.password=Happypet_2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.forward-headers-strategy=framework

app.base-url=https://happypett.duckdns.org
